# Generated by Django 4.1.7 on 2023-03-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ifsc', models.CharField(max_length=255)),
                ('bank_id', models.IntegerField()),
                ('branch', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=1080)),
                ('city', models.CharField(max_length=500)),
                ('district', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('bank_name', models.CharField(max_length=255)),
            ],
        ),
    ]
